[workspace]
name = "ml-env-204"
platforms = ["linux-64"]
channels = ["conda-forge"]

[dependencies]
python = "3.12.*"
numpy = "*"
matplotlib = "*"
pandas = ">=3.0.2,<4"
jupyterlab = "*"
jupytext = "*"
scikit-learn = ">=1.8.0,<2"
transformers = "*"
nltk = "*"
langchain = "*"
langchain-community = "*"
langchain-ollama = "*"
langgraph = "*"
torchvision = "*"
pillow = "*"
tqdm = "*"
fastapi = ">=0.136.0,<0.137"
uvicorn = "*"
sqlalchemy = ">=2.0"
pydantic = "*"
requests = "*"
httpx = "*"
loguru = "*"

[pypi-dependencies]
sqlite-vec = "*"

[feature.cuda.system-requirements]
cuda = "12"

[feature.cuda.dependencies]
pytorch = { version = ">=2.6", build = "*cuda*" }

[feature.cpu.dependencies]
pytorch = { version = ">=2.6", build = "*cpu*" }

[environments]
default = { features = ["cuda"] }
cpu = { features = ["cpu"] }

[activation.env]
HF_HOME = "$PIXI_PROJECT_ROOT/data/hf_cache"
